name: Deploy github pages

on:
  push:
    branches:
      - master
      - test/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GitHub
        run: |
          git config user.name "fnaoto"
          git config user.email "f.naoto832+github@gmail.com"
          git remote set-url origin https://fnaoto:${{ secrets.GITHUB_TOKEN }}@github.com/fnaoto/home
      - name: Install
        run: yarn
      - name: Deploy
        run: yarn deploy
