name: Deploy github pages

on:
  push:
    branches:
      - master
      - test/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GitHub
        run: |
          cat gitconfig.b64 | base64 -d > ~/.gitconfig
          git remote set-url origin https://fnaoto:${{ secrets.GITHUB_TOKEN }}@github.com/fnaoto/home
      - name: Install
        run: yarn
      - name: Deploy
        run: yarn deploy
